project_id = "csenulbdattrynafibqw"

[functions.make-call]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.twilio-status-callback]
verify_jwt = false

[functions.create-voice-clone]
verify_jwt = false

[functions.preview-voice]
verify_jwt = false

[functions.delete-voice-clone]
verify_jwt = false

[functions.parse-voice-reminder]
verify_jwt = false